import { useState, useEffect } from 'react'
import { useParams } from 'react-router-dom'
import { api } from '../../api'
import { LeakageBadge } from '../../components/RiskBadge'
import { Sparkles, Loader2 } from 'lucide-react'

export default function CaseDetail() {
  const { flagId } = useParams()
  const [flag, setFlag] = useState(null)
  const [loading, setLoading] = useState(true)
  const [aiLoading, setAiLoading] = useState(false)
  const [evidenceSource, setEvidenceSource] = useState('template')

  useEffect(() => {
    if (!flagId) return
    api.getFlag(flagId).then(res => {
      setFlag(res.data)
      setLoading(false)
      setEvidenceSource('template')
    }).catch(e => {
      console.error(e)
      setLoading(false)
    })
  }, [flagId])

  const handleStatusChange = async (newStatus) => {
    try {
      await api.updateFlagStatus(flagId, newStatus)
      setFlag({ ...flag, status: newStatus })
    } catch (e) {
      console.error(e)
    }
  }

  const handleGenerateAIEvidence = async () => {
    setAiLoading(true)
    try {
      const res = await api.generateEvidence(flagId)
      setFlag({ ...flag, evidence: res.data.evidence })
      setEvidenceSource(res.data.source)
    } catch (e) {
      console.error(e)
    } finally {
      setAiLoading(false)
    }
  }

  if (loading) return <div className="p-8 text-text-secondary font-data">Loading case file...</div>
  if (!flag) return <div className="p-8 text-text-secondary font-data">Case not found.</div>

  const getBannerColor = (label) => {
    if (label === 'CRITICAL') return 'bg-risk-critical'
    if (label === 'HIGH') return 'bg-risk-high'
    if (label === 'MEDIUM') return 'bg-risk-medium'
    return 'bg-risk-low'
  }

  return (
    <div className="p-8 font-sans">
      <div className="flex gap-6">
        {/* LEFT COLUMN (60%) */}
        <div className="w-3/5 flex flex-col gap-6">
          <div className="bg-surface-lowest rounded-lg shadow-sm overflow-hidden">
            <div className={`h-2 ${getBannerColor(flag.risk_label)} w-full`}></div>
            <div className="p-6">
              <div className="flex justify-between items-start mb-4">
                <div>
                  <h1 className="text-3xl font-bold tracking-tight text-text-primary">{flag.beneficiary_name}</h1>
                  <p className="text-sm font-data text-text-secondary mt-1">{flag.district} · {flag.scheme}</p>
                </div>
                <div className="text-right">
                  <div className="font-mono text-sm text-text-secondary">Flag ID: {flag.flag_id}</div>
                  <div className="font-mono text-sm text-text-secondary mt-1">Status: {flag.status || 'OPEN'}</div>
                </div>
              </div>
              <LeakageBadge type={flag.leakage_type} />
            </div>
          </div>

          <div className="bg-surface-lowest border border-border-subtle rounded-sm p-6 shadow-[inset_0_0_20px_rgba(0,0,0,0.02)]">
            <div className="flex items-center justify-between mb-3">
              <span className="text-xs font-bold uppercase tracking-widest text-text-secondary font-sans">Evidence Record</span>
              <button
                onClick={handleGenerateAIEvidence}
                disabled={aiLoading || evidenceSource === 'ai'}
                className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold font-sans rounded-sm bg-gradient-to-b from-primary-override to-shell text-white hover:shadow-md disabled:opacity-50 transition-all"
              >
                {aiLoading ? <Loader2 size={14} className="animate-spin" /> : <Sparkles size={14} />}
                {aiLoading ? 'Generating...' : evidenceSource === 'ai' ? 'AI Evidence ✓' : 'Generate AI Evidence'}
              </button>
            </div>
            <pre className="font-mono text-sm text-text-primary whitespace-pre-wrap leading-relaxed">
{`┌─────────────────────────────────────────────┐
│  EVIDENCE RECORD                            │
│  Flag ID: ${flag.flag_id.padEnd(25)} │
│  Generated by EduGuard Intelligence Unit    │
│  Source: ${(evidenceSource === 'ai' ? 'Groq AI (LLaMA 3.3 70B)' : 'Template Engine').padEnd(27)} │
├─────────────────────────────────────────────┤
│                                             │
│  ${flag.evidence || "No evidence string generated by AI layer."}                               
│                                             │
│  DATA SOURCES: Payment Ledger · Death       │
│  Registry · U-DISE · Aadhaar Registry       │
└─────────────────────────────────────────────┘`}
            </pre>
          </div>

          <div className="bg-surface-lowest p-6 rounded-lg shadow-sm">
            <h3 className="text-sm font-bold uppercase tracking-widest text-text-secondary mb-4">Data Records</h3>
            <div className="grid grid-cols-2 gap-4 text-sm font-data">
              <div className="bg-surface-low p-4 rounded">
                <span className="text-text-secondary block text-xs mb-1 uppercase font-bold">Payment Amount</span>
                <span className="font-mono font-medium text-lg text-text-primary">₹{flag.payment_amount?.toLocaleString('en-IN') || 0}</span>
              </div>
              <div className="bg-surface-low p-4 rounded">
                <span className="text-text-secondary block text-xs mb-1 uppercase font-bold">Disbursement Date</span>
                <span className="font-medium text-text-primary">{flag.payment_date || 'N/A'}</span>
              </div>
            </div>
          </div>
        </div>

        {/* RIGHT COLUMN (40%) */}
        <div className="w-2/5 flex flex-col gap-6">
          <div className="bg-surface-lowest p-6 rounded-lg shadow-sm text-center">
            <h3 className="text-sm font-bold uppercase tracking-widest text-text-secondary mb-4">Risk Assessment</h3>
            <div className={`text-6xl font-bold font-sans ${flag.risk_label === 'CRITICAL' ? 'text-risk-critical' : 'text-primary-override'}`}>
              {flag.risk_score}
            </div>
            <div className="text-sm font-data font-semibold text-text-secondary mt-2">RISK SCORE / 100</div>
          </div>

          <div className="bg-surface-lowest p-6 rounded-lg shadow-sm">
            <h3 className="text-sm font-bold uppercase tracking-widest text-text-secondary mb-4">Recommended Action</h3>
            <p className="text-sm text-text-primary font-data bg-surface-low p-4 rounded border-l-4 border-primary-override leading-relaxed">
              {flag.recommended_action || "Manual review required by District Finance Officer."}
            </p>
          </div>

          <div className="bg-surface-lowest p-6 rounded-lg shadow-sm">
            <h3 className="text-sm font-bold uppercase tracking-widest text-text-secondary mb-4">Status Management</h3>
            <select 
              value={flag.status || 'OPEN'} 
              onChange={(e) => handleStatusChange(e.target.value)}
              className="w-full bg-surface-lowest border border-border-subtle text-text-primary text-sm rounded p-2.5 mb-4 font-sans font-semibold outline-none focus:ring-2 focus:ring-primary-override"
            >
              <option value="OPEN">OPEN - Pending Review</option>
              <option value="ASSIGNED">ASSIGNED - Field Verification</option>
              <option value="RESOLVED">RESOLVED - Case Closed</option>
            </select>

            <button className="w-full bg-gradient-to-b from-primary-override to-shell text-white text-sm font-bold rounded p-2.5 hover:shadow-lg transition-all shadow-sm">
              Save Changes
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
