"""Minimal mock datasets used only when real JSON data files are unavailable."""

MOCK_BENEFICIARIES = [
    {
        "beneficiary_id": "BEN-GJ-01-0001",
        "aadhaar_hash": "aadhaar001",
        "name": "Riya Patel",
        "name_variants": ["Riyaben Patel"],
        "dob": "2007-04-15",
        "gender": "F",
        "caste_category": "OBC",
        "district": "Gandhinagar",
        "taluka": "Mansa",
        "bank_account_hash": "bank001",
        "is_deceased": True,
        "death_date": "2025-01-03",
    },
    {
        "beneficiary_id": "BEN-GJ-01-0002",
        "aadhaar_hash": "aadhaar002",
        "name": "Neha Shah",
        "name_variants": ["Nehaben Shah"],
        "dob": "2008-09-11",
        "gender": "F",
        "caste_category": "GENERAL",
        "district": "Ahmedabad",
        "taluka": "Daskroi",
        "bank_account_hash": "bank002",
        "is_deceased": False,
        "death_date": None,
    },
    {
        "beneficiary_id": "BEN-GJ-01-0003",
        "aadhaar_hash": "aadhaar002",
        "name": "Neha Saha",
        "name_variants": ["Neha Saah"],
        "dob": "2008-09-11",
        "gender": "F",
        "caste_category": "GENERAL",
        "district": "Ahmedabad",
        "taluka": "Daskroi",
        "bank_account_hash": "bank003",
        "is_deceased": False,
        "death_date": None,
    },
    {
        "beneficiary_id": "BEN-GJ-01-0004",
        "aadhaar_hash": "aadhaar004",
        "name": "Krunal Mehta",
        "name_variants": ["Krunal M"],
        "dob": "2007-01-01",
        "gender": "M",
        "caste_category": "SC",
        "district": "Surat",
        "taluka": "Choryasi",
        "bank_account_hash": "bank004",
        "is_deceased": False,
        "death_date": None,
    },
    {
        "beneficiary_id": "BEN-GJ-01-0005",
        "aadhaar_hash": "aadhaar005",
        "name": "Mansi Trivedi",
        "name_variants": ["Mansiben Trivedi"],
        "dob": "2006-07-02",
        "gender": "F",
        "caste_category": "SEBC",
        "district": "Rajkot",
        "taluka": "Rajkot",
        "bank_account_hash": "bank005",
        "is_deceased": False,
        "death_date": None,
    },
    {
        "beneficiary_id": "BEN-GJ-01-0006",
        "aadhaar_hash": "aadhaar006",
        "name": "Mansi Trivedee",
        "name_variants": ["Mansi T"],
        "dob": "2006-07-02",
        "gender": "F",
        "caste_category": "SEBC",
        "district": "Rajkot",
        "taluka": "Rajkot",
        "bank_account_hash": "bank005",
        "is_deceased": False,
        "death_date": None,
    },
]

MOCK_UDISE = [
    {
        "beneficiary_id": "BEN-GJ-01-0001",
        "udise_code": "24040100101",
        "school_name": "Shri Sarvodaya High School",
        "standard": 11,
        "stream": "Science",
        "attendance_pct": 89.0,
        "marks_pct": 83.2,
        "enrollment_status": "ACTIVE",
        "academic_year": "2024-25",
    },
    {
        "beneficiary_id": "BEN-GJ-01-0002",
        "udise_code": "24040100102",
        "school_name": "Vidhya Mandir",
        "standard": 12,
        "stream": "Science",
        "attendance_pct": 74.5,
        "marks_pct": 78.8,
        "enrollment_status": "ACTIVE",
        "academic_year": "2024-25",
    },
]

MOCK_DEATH_REGISTRY = [
    {
        "aadhaar_hash": "aadhaar001",
        "name": "Riya Patel",
        "death_date": "2025-01-03",
        "district": "Gandhinagar",
    }
]

MOCK_PAYMENTS = [
    {
        "payment_id": "PAY-NLY-00001",
        "beneficiary_id": "BEN-GJ-01-0001",
        "scheme": "NLY",
        "amount": 25000,
        "payment_date": "2025-03-12",
        "credit_date": "2025-03-12",
        "withdrawal_date": None,
        "bank_account_hash": "bank001",
        "payment_status": "CREDITED",
    },
    {
        "payment_id": "PAY-NSV-00002",
        "beneficiary_id": "BEN-GJ-01-0002",
        "scheme": "NSVSY",
        "amount": 10000,
        "payment_date": "2025-01-01",
        "credit_date": "2025-01-01",
        "withdrawal_date": None,
        "bank_account_hash": "bank002",
        "payment_status": "CREDITED",
    },
    {
        "payment_id": "PAY-NLY-00003",
        "beneficiary_id": "BEN-GJ-01-0002",
        "scheme": "NLY",
        "amount": 25000,
        "payment_date": "2025-01-15",
        "credit_date": "2025-01-15",
        "withdrawal_date": "2025-01-20",
        "bank_account_hash": "bank002",
        "payment_status": "WITHDRAWN",
    },
    {
        "payment_id": "PAY-MGM-00004",
        "beneficiary_id": "BEN-GJ-01-0003",
        "scheme": "MGMS",
        "amount": 5000,
        "payment_date": "2025-02-02",
        "credit_date": "2025-02-02",
        "withdrawal_date": "2025-02-07",
        "bank_account_hash": "bank003",
        "payment_status": "WITHDRAWN",
    },
]